# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_swig_vs')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_swig_vs')
    _swig_vs = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_swig_vs', [dirname(__file__)])
        except ImportError:
            import _swig_vs
            return _swig_vs
        try:
            _mod = imp.load_module('_swig_vs', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _swig_vs = swig_import_helper()
    del swig_import_helper
else:
    import _swig_vs
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _swig_vs.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _swig_vs.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _swig_vs.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _swig_vs.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _swig_vs.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _swig_vs.SwigPyIterator_equal(self, x)

    def copy(self):
        return _swig_vs.SwigPyIterator_copy(self)

    def next(self):
        return _swig_vs.SwigPyIterator_next(self)

    def __next__(self):
        return _swig_vs.SwigPyIterator___next__(self)

    def previous(self):
        return _swig_vs.SwigPyIterator_previous(self)

    def advance(self, n):
        return _swig_vs.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _swig_vs.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _swig_vs.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _swig_vs.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _swig_vs.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _swig_vs.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _swig_vs.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _swig_vs.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _swig_vs.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swig_vs.IntVector___nonzero__(self)

    def __bool__(self):
        return _swig_vs.IntVector___bool__(self)

    def __len__(self):
        return _swig_vs.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _swig_vs.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swig_vs.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swig_vs.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swig_vs.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swig_vs.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swig_vs.IntVector___setitem__(self, *args)

    def pop(self):
        return _swig_vs.IntVector_pop(self)

    def append(self, x):
        return _swig_vs.IntVector_append(self, x)

    def empty(self):
        return _swig_vs.IntVector_empty(self)

    def size(self):
        return _swig_vs.IntVector_size(self)

    def swap(self, v):
        return _swig_vs.IntVector_swap(self, v)

    def begin(self):
        return _swig_vs.IntVector_begin(self)

    def end(self):
        return _swig_vs.IntVector_end(self)

    def rbegin(self):
        return _swig_vs.IntVector_rbegin(self)

    def rend(self):
        return _swig_vs.IntVector_rend(self)

    def clear(self):
        return _swig_vs.IntVector_clear(self)

    def get_allocator(self):
        return _swig_vs.IntVector_get_allocator(self)

    def pop_back(self):
        return _swig_vs.IntVector_pop_back(self)

    def erase(self, *args):
        return _swig_vs.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _swig_vs.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _swig_vs.IntVector_push_back(self, x)

    def front(self):
        return _swig_vs.IntVector_front(self)

    def back(self):
        return _swig_vs.IntVector_back(self)

    def assign(self, n, x):
        return _swig_vs.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _swig_vs.IntVector_resize(self, *args)

    def insert(self, *args):
        return _swig_vs.IntVector_insert(self, *args)

    def reserve(self, n):
        return _swig_vs.IntVector_reserve(self, n)

    def capacity(self):
        return _swig_vs.IntVector_capacity(self)
    __swig_destroy__ = _swig_vs.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _swig_vs.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _swig_vs.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swig_vs.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _swig_vs.DoubleVector___bool__(self)

    def __len__(self):
        return _swig_vs.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _swig_vs.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swig_vs.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swig_vs.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swig_vs.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swig_vs.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swig_vs.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _swig_vs.DoubleVector_pop(self)

    def append(self, x):
        return _swig_vs.DoubleVector_append(self, x)

    def empty(self):
        return _swig_vs.DoubleVector_empty(self)

    def size(self):
        return _swig_vs.DoubleVector_size(self)

    def swap(self, v):
        return _swig_vs.DoubleVector_swap(self, v)

    def begin(self):
        return _swig_vs.DoubleVector_begin(self)

    def end(self):
        return _swig_vs.DoubleVector_end(self)

    def rbegin(self):
        return _swig_vs.DoubleVector_rbegin(self)

    def rend(self):
        return _swig_vs.DoubleVector_rend(self)

    def clear(self):
        return _swig_vs.DoubleVector_clear(self)

    def get_allocator(self):
        return _swig_vs.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _swig_vs.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _swig_vs.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _swig_vs.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _swig_vs.DoubleVector_push_back(self, x)

    def front(self):
        return _swig_vs.DoubleVector_front(self)

    def back(self):
        return _swig_vs.DoubleVector_back(self)

    def assign(self, n, x):
        return _swig_vs.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _swig_vs.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _swig_vs.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _swig_vs.DoubleVector_reserve(self, n)

    def capacity(self):
        return _swig_vs.DoubleVector_capacity(self)
    __swig_destroy__ = _swig_vs.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _swig_vs.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)


def no_arg():
    return _swig_vs.no_arg()
no_arg = _swig_vs.no_arg

def num_arg(a):
    return _swig_vs.num_arg(a)
num_arg = _swig_vs.num_arg

def num_argd(a):
    return _swig_vs.num_argd(a)
num_argd = _swig_vs.num_argd

def numnum_arg(a, b):
    return _swig_vs.numnum_arg(a, b)
numnum_arg = _swig_vs.numnum_arg

def vect(ve):
    return _swig_vs.vect(ve)
vect = _swig_vs.vect

def stri(st):
    return _swig_vs.stri(st)
stri = _swig_vs.stri

def loop(x):
    return _swig_vs.loop(x)
loop = _swig_vs.loop
class class_(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, class_, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, class_, name)
    __repr__ = _swig_repr

    def func1(self, arg2, arg3):
        return _swig_vs.class__func1(self, arg2, arg3)

    def func2(self, arg2):
        return _swig_vs.class__func2(self, arg2)

    def __init__(self):
        this = _swig_vs.new_class_()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _swig_vs.delete_class_
    __del__ = lambda self: None
class__swigregister = _swig_vs.class__swigregister
class__swigregister(class_)


def arr(seq):
    return _swig_vs.arr(seq)
arr = _swig_vs.arr

def arr2d(seq):
    return _swig_vs.arr2d(seq)
arr2d = _swig_vs.arr2d

def return_array(arr, k):
    return _swig_vs.return_array(arr, k)
return_array = _swig_vs.return_array

def two_arr(seq1, seq2):
    return _swig_vs.two_arr(seq1, seq2)
two_arr = _swig_vs.two_arr

def predict(inarr, outarr):
    return _swig_vs.predict(inarr, outarr)
predict = _swig_vs.predict
class Fit_predict(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Fit_predict, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Fit_predict, name)
    __repr__ = _swig_repr

    def _partial_fit(self, input_array, input_class):
        return _swig_vs.Fit_predict__partial_fit(self, input_array, input_class)

    def _predict(self, input_array, prediction):
        return _swig_vs.Fit_predict__predict(self, input_array, prediction)

    def __init__(self):
        this = _swig_vs.new_Fit_predict()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _swig_vs.delete_Fit_predict
    __del__ = lambda self: None
Fit_predict_swigregister = _swig_vs.Fit_predict_swigregister
Fit_predict_swigregister(Fit_predict)

# This file is compatible with both classic and new-style classes.


