# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_swig_nump')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_swig_nump')
    _swig_nump = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_swig_nump', [dirname(__file__)])
        except ImportError:
            import _swig_nump
            return _swig_nump
        try:
            _mod = imp.load_module('_swig_nump', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _swig_nump = swig_import_helper()
    del swig_import_helper
else:
    import _swig_nump
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def arr(seq):
    return _swig_nump.arr(seq)
arr = _swig_nump.arr

def arr2d(seq):
    return _swig_nump.arr2d(seq)
arr2d = _swig_nump.arr2d

def return_array(arr, k):
    return _swig_nump.return_array(arr, k)
return_array = _swig_nump.return_array

def two_arr(seq1, seq2):
    return _swig_nump.two_arr(seq1, seq2)
two_arr = _swig_nump.two_arr

def predict(inarr, outarr):
    return _swig_nump.predict(inarr, outarr)
predict = _swig_nump.predict
class Fit_predict(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Fit_predict, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Fit_predict, name)
    __repr__ = _swig_repr

    def _partial_fit(self, input_array, input_class):
        return _swig_nump.Fit_predict__partial_fit(self, input_array, input_class)

    def _predict(self, input_array, prediction):
        return _swig_nump.Fit_predict__predict(self, input_array, prediction)

    def __init__(self):
        this = _swig_nump.new_Fit_predict()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _swig_nump.delete_Fit_predict
    __del__ = lambda self: None
Fit_predict_swigregister = _swig_nump.Fit_predict_swigregister
Fit_predict_swigregister(Fit_predict)

# This file is compatible with both classic and new-style classes.


