# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_no_args')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_no_args')
    _no_args = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_no_args', [dirname(__file__)])
        except ImportError:
            import _no_args
            return _no_args
        try:
            _mod = imp.load_module('_no_args', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _no_args = swig_import_helper()
    del swig_import_helper
else:
    import _no_args
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _no_args.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _no_args.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _no_args.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _no_args.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _no_args.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _no_args.SwigPyIterator_equal(self, x)

    def copy(self):
        return _no_args.SwigPyIterator_copy(self)

    def next(self):
        return _no_args.SwigPyIterator_next(self)

    def __next__(self):
        return _no_args.SwigPyIterator___next__(self)

    def previous(self):
        return _no_args.SwigPyIterator_previous(self)

    def advance(self, n):
        return _no_args.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _no_args.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _no_args.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _no_args.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _no_args.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _no_args.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _no_args.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _no_args.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _no_args.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _no_args.IntVector___nonzero__(self)

    def __bool__(self):
        return _no_args.IntVector___bool__(self)

    def __len__(self):
        return _no_args.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _no_args.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _no_args.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _no_args.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _no_args.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _no_args.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _no_args.IntVector___setitem__(self, *args)

    def pop(self):
        return _no_args.IntVector_pop(self)

    def append(self, x):
        return _no_args.IntVector_append(self, x)

    def empty(self):
        return _no_args.IntVector_empty(self)

    def size(self):
        return _no_args.IntVector_size(self)

    def swap(self, v):
        return _no_args.IntVector_swap(self, v)

    def begin(self):
        return _no_args.IntVector_begin(self)

    def end(self):
        return _no_args.IntVector_end(self)

    def rbegin(self):
        return _no_args.IntVector_rbegin(self)

    def rend(self):
        return _no_args.IntVector_rend(self)

    def clear(self):
        return _no_args.IntVector_clear(self)

    def get_allocator(self):
        return _no_args.IntVector_get_allocator(self)

    def pop_back(self):
        return _no_args.IntVector_pop_back(self)

    def erase(self, *args):
        return _no_args.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _no_args.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _no_args.IntVector_push_back(self, x)

    def front(self):
        return _no_args.IntVector_front(self)

    def back(self):
        return _no_args.IntVector_back(self)

    def assign(self, n, x):
        return _no_args.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _no_args.IntVector_resize(self, *args)

    def insert(self, *args):
        return _no_args.IntVector_insert(self, *args)

    def reserve(self, n):
        return _no_args.IntVector_reserve(self, n)

    def capacity(self):
        return _no_args.IntVector_capacity(self)
    __swig_destroy__ = _no_args.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _no_args.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _no_args.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _no_args.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _no_args.DoubleVector___bool__(self)

    def __len__(self):
        return _no_args.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _no_args.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _no_args.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _no_args.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _no_args.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _no_args.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _no_args.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _no_args.DoubleVector_pop(self)

    def append(self, x):
        return _no_args.DoubleVector_append(self, x)

    def empty(self):
        return _no_args.DoubleVector_empty(self)

    def size(self):
        return _no_args.DoubleVector_size(self)

    def swap(self, v):
        return _no_args.DoubleVector_swap(self, v)

    def begin(self):
        return _no_args.DoubleVector_begin(self)

    def end(self):
        return _no_args.DoubleVector_end(self)

    def rbegin(self):
        return _no_args.DoubleVector_rbegin(self)

    def rend(self):
        return _no_args.DoubleVector_rend(self)

    def clear(self):
        return _no_args.DoubleVector_clear(self)

    def get_allocator(self):
        return _no_args.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _no_args.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _no_args.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _no_args.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _no_args.DoubleVector_push_back(self, x)

    def front(self):
        return _no_args.DoubleVector_front(self)

    def back(self):
        return _no_args.DoubleVector_back(self)

    def assign(self, n, x):
        return _no_args.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _no_args.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _no_args.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _no_args.DoubleVector_reserve(self, n)

    def capacity(self):
        return _no_args.DoubleVector_capacity(self)
    __swig_destroy__ = _no_args.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _no_args.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)


def no_arg():
    return _no_args.no_arg()
no_arg = _no_args.no_arg

def num_arg(a):
    return _no_args.num_arg(a)
num_arg = _no_args.num_arg

def num_argd(a):
    return _no_args.num_argd(a)
num_argd = _no_args.num_argd

def numnum_arg(a, b):
    return _no_args.numnum_arg(a, b)
numnum_arg = _no_args.numnum_arg

def arr(arr):
    return _no_args.arr(arr)
arr = _no_args.arr

def vect(ve):
    return _no_args.vect(ve)
vect = _no_args.vect

def stri(st):
    return _no_args.stri(st)
stri = _no_args.stri

def loop(x):
    return _no_args.loop(x)
loop = _no_args.loop
# This file is compatible with both classic and new-style classes.


